import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// import Navbar from './component/Navbar'
// import Footer from './component/Footer'
// import Layout from './component/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Next js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1>Hello World!!!</h1>
{/* <Navbar/>
<Layout/>
<Footer/> */}
      </main>
    </>
  )
}
